### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [mkihn/prj-rev-bwfs-dasmoto#5]
https://github.com/mkihn/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/Resources/css/style.css#L1-L27

You have an opportunity to remove repetition from your code.

Since all of the text on the page is the same font, you should put those font-family styles into a single selector.

```css
h1, h2, h3, p, span {
  font-family: Helvetica;
}
```

Or, using the universal selector `*`

```css
* {
  font-family: Helvetica;
}
```
